### Jithin Sasikumar

This notebook addresses the major issues when implementing **feature attribution methods (SHAP and LIME)** for LSTM time-series model. It contains data pre-processing, model prediction, SHAP implementation for our model along with the issues and my observations. I have also added the comparison of our model with two other models trained on different datasets for different problems.

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import shap
import tensorflow as tf

## Loading train and test data for pre-processing

1. The data has **25 features**, each representing sensor information from a specific channel of the respective satellite. 
2. The data is one-hot encoded.

In [3]:
#Train data
train_arr = np.load('D:/DLR/telemanom/data/train/A-1.npy')
data_train = pd.DataFrame(train_arr)
print(data_train.shape)

data_train

(2880, 25)

,0,1,2,3,4,5,6,7,8,9,...,15,16,17,18,19,20,21,22,23,24
0,0.999,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.999,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.999,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.999,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.999,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2875,0.999,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2876,0.999,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2877,0.999,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2878,0.999,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2879,0.999,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [4]:
#Test data
test_arr = np.load('D:/DLR/telemanom/data/test/A-1.npy')
test = pd.DataFrame(test_arr)
print(test.shape)

test

(8640, 25)

,0,1,2,3,4,5,6,7,8,9,...,15,16,17,18,19,20,21,22,23,24
0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8635,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
8636,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
8637,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
8638,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
8639,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [34]:
y_hat = np.load('D:/DLR/telemanom/data/2018-05-19_15.00.10/y_hat/A-1.npy')
y_hat_df = pd.DataFrame(y_hat)
y_hat_df

             0
0     0.976049
1     0.976191
2     0.976298
3     0.976378
4     0.976436
...        ...
8375  0.976578
8376  0.976569
8377  0.976559
8378  0.976551
8379  0.976543

[8380 rows x 1 columns]

## Loading pre-trained model (NASA)

In [6]:
print(tf.__version__)
model = tf.keras.models.load_model('D:/DLR/telemanom/data/2018-05-19_15.00.10/models/A-1.h5')

2.0.0

In [8]:
print(model)
#Displaying model configurations and properities
model.summary()

<tensorflow.python.keras.engine.sequential.Sequential object at 0x00000251BE969108>
Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #
=================================================================
lstm_5 (LSTM)                (None, None, 80)          33920
_________________________________________________________________
dropout_5 (Dropout)          (None, None, 80)          0
_________________________________________________________________
lstm_6 (LSTM)                (None, 80)                51520
_________________________________________________________________
dropout_6 (Dropout)          (None, 80)                0
_________________________________________________________________
dense_3 (Dense)              (None, 10)                810
_________________________________________________________________
activation_3 (Activation)    (None, 10)                0
=================================================================
Total params: 86,250
Trainable params: 86,250
Non-trainable params: 0
_________________________________________________________________

## Data Pre-processing
1. The data is pre-processed with respect to its time steps as batches. As LSTM accepts only 3D data as input, the actual data is transformed into three dimensional array in the format **(data_samples, n_timesteps, n_features). => (2620, 250, 25)** <br>
3. During pre-processing, in order to restructure the data to represent like a supervised learning problem, previous time steps are used as input variables and the next time step is used as output variable which is called **sliding window technique for time-series** <br>
4. Here, the number of previous timesteps is **250** as per config.yaml. Thus our data will be trained and model makes the predictions by processing each 250 timesteps data with 25 features, **ten times**. 
5. Thus the number of predictions will be 10. The output shape will be **(2620, 10) = > (data_samples, n_predictions).**

<br>
The same is demonstrated in the below code.

In [9]:
#train data
train=False
data = []
for i in range(len(data_train) - 250 - 10):
    data.append(data_train[i:i + 250 + 10])
data = np.array(data)

assert len(data.shape) == 3

if not train:
    X_train = data[:, :-10, :]
    y_train = data[:, -10:, 0]

print("X:",X_train.shape)
print("Y:",y_train.shape)

X: (2620, 250, 25)
Y: (2620, 10)

In [15]:
#For test data
train=False
data = []
for i in range(len(test_arr) - 250 - 10):
    data.append(test_arr[i:i + 250 + 10])
data = np.array(data)

assert len(data.shape) == 3

if not train:
    X_test = data[:, :-10, :]
    y_test = data[:, -10:, 0]

## Model Prediction
1. As explained in the above cell, the model makes predictions with our pre-processed test data.
2. Before predicting the value, actual data is converted into **batches** and each batch is given into model seperately where the model uses previous batch information for current batch processsing and then predicts the output value. <br>
3. Thus each batch contains **260 data samples, 250 timesteps and 25 features** => **(260, 250, 25)**.
4. Our model outputs 10 predictions for 260 data samples as => **(260,10) predictions (y_hat)** for each batch given.

In [12]:
num_batches = int((y_test.shape[0] - 250)/ 70)
for i in range(0, num_batches + 1):
    prior_idx = i * 70
    idx = (i + 1) * 70
    
    if i + 1 == num_batches + 1:
        idx = y_test.shape[0]
    
    X_test_batch = X_test[prior_idx:idx]
    y_test_batch = y_test[prior_idx:idx]
    y_hat_batch = model.predict(X_test_batch)

In [14]:
print("X batch in test data:",X_test_batch.shape)
print("Y batch in test data:",y_test_batch.shape)
print("y_hat predictions from test data:",y_hat_batch.shape)

X batch in test data: (260, 250, 25)
Y batch in test data: (260, 10)
y_hat predictions from test data: (260, 10)

## SHAP Implementation

**Reference:** <br>
https://arxiv.org/pdf/1903.02407.pdf <br>
https://github.com/liuyilin950623/SHAP_on_Autoencoder

In [16]:
#Picking a data point with largest reconstruction or prediction error

X_reconstruction_standard = model.predict(X_test_batch)
rec_err = np.linalg.norm(y_test_batch - X_reconstruction_standard, axis = 1)
idx = list(rec_err).index(max(rec_err))
df = pd.DataFrame(data = X_reconstruction_standard[idx], columns = ['reconstruction_loss'])
df.T

,0,1,2,3,4,5,6,7,8,9
reconstruction_loss,0.96608,0.967489,0.956203,0.964819,0.960538,0.966676,0.952093,0.96608,0.966304,0.968249

In [17]:
print("Model Prediction output shape for test batch:",X_reconstruction_standard.shape)
print("\nActual Value y:\n",y_test_batch[1])
print("Predicted Value y_hat:\n",X_reconstruction_standard[1])
print("\nFirst five predictions:\n",X_reconstruction_standard[0:5])
print("\nFirst 5 Prediction (or) Re-construction error:\n",rec_err[0:5])

Model Prediction output shape for test batch: (260, 10)

Actual Value y:
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
Predicted Value y_hat:
 [0.9739516  0.9887368  0.9738245  0.99259615 0.9800745  0.98507845
 0.9748681  0.99089825 0.9805185  0.9821451 ]

First five predictions:
 [[0.9733607  0.9879205  0.9732397  0.9919983  0.9796158  0.9846846
  0.9742988  0.990171   0.9798947  0.9817468 ]
 [0.9739516  0.9887368  0.9738245  0.99259615 0.9800745  0.98507845
  0.9748681  0.99089825 0.9805185  0.9821451 ]
 [0.97446465 0.9894272  0.97432685 0.99309766 0.98047465 0.9854017
  0.9753439  0.99151456 0.98105055 0.9824883 ]
 [0.9749013  0.9900011  0.9747505  0.9935121  0.9808161  0.9856611
  0.9757351  0.99203014 0.981495   0.9827764 ]
 [0.97526526 0.99046975 0.9751019  0.9938499  0.9811022  0.9858655
  0.97605145 0.9924544  0.9818594  0.9830123 ]]

First 5 Prediction (or) Re-construction error:
 [0.06148452 0.0598148  0.05840042 0.05722382 0.05626203]

In [18]:
# Selecting top 5 features from the error list
def sort_by_absolute(df, index):
    df_abs = df.apply(lambda x: abs(x))
    df_abs = df_abs.sort_values('reconstruction_loss', ascending = False)
    df = df.loc[df_abs.index,:]
    return df
sort_by_absolute(df, idx).T

,9,1,5,8,7,0,3,4,2,6
reconstruction_loss,0.968249,0.967489,0.966676,0.966304,0.96608,0.96608,0.964819,0.960538,0.956203,0.952093

In [19]:
top_5_features = sort_by_absolute(df, idx).iloc[:5,:]
top_5_features.T

                            9         1         5         8        7
reconstruction_loss  0.968249  0.967489  0.966676  0.966304  0.96608

In [20]:
# using SHAP
for i in top_5_features.index:
    explainer_autoencoder = shap.KernelExplainer(model.predict, X_test_batch)
    shap_values = explainer_autoencoder.shap_values(X_test_batch[idx,:,:])

Using 260 background data samples could cause slower run times. Consider using shap.sample(data, K) or shap.kmeans(data, K) to summarize the background as K samples.

HBox(children=(HTML(value=''), FloatProgress(value=0.0, max=250.0), HTML(value='')))

IndexError: index 25 is out of bounds for axis 1 with size 25

In [22]:
model.summary()

print("\nX test batch-",X_test_batch.shape)

print("\ny test batch",y_test_batch.shape)

print("\ny hat batch",y_hat_batch.shape)

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #
=================================================================
lstm_5 (LSTM)                (None, None, 80)          33920
_________________________________________________________________
dropout_5 (Dropout)          (None, None, 80)          0
_________________________________________________________________
lstm_6 (LSTM)                (None, 80)                51520
_________________________________________________________________
dropout_6 (Dropout)          (None, 80)                0
_________________________________________________________________
dense_3 (Dense)              (None, 10)                810
_________________________________________________________________
activation_3 (Activation)    (None, 10)                0
=================================================================
Total params: 86,250
Trainable params: 86,250
Non-trainable params: 0
_________________________________________________________________

X test batch- (260, 250, 25)

y test batch (260, 10)

y hat batch (260, 10)

### Issues with Feature Attribution Methods (SHAP & LIME):

**My Observations:**

1. As our LSTM network is designed to predict the values in 10 predictions for entire batches, it's input layer accepts data of shape (260, 250, 25) and output layer outputs predictions in shape (260, 10). <br>
2. Here, those 10 predictions are called **lag observations (or) lag features.** as we use previous timestep information. <br>
3. When we apply our model and data to any feature attribution methods like **SHAP, LIME** etc. they expect the features to be the same, only then these methods can assign importance scores to every feature and return the most contributing features for the prediction [In our case - features that contributed for anomaly]. 
4. Thus, the ground rule is input and output features should be equal (i.e.) If input layer has **25 features**, then the output layer also should have 25 features. But there is no actual issue with our model as it uses 25 features to make predictions and the output **10 predictions** are just lag features and not actual features which creates a conflict. <br>
5. Thus SHAP, LIME assumes the features to be inconsistent as they don't match and throws the above error. <br>
6. To illustrate in simpler terms, the input shape of the network should be equal to it's output shape. <br>

The above error applies to LIME as well.

## Comparison
To justify the observations, I have compared my implementaion with some other implementations as below.

### Our dataset (NASA)

In [24]:
print("X train - ",X_train.shape)
print("y train -",y_train.shape)

print("\nX test batch-",X_test_batch.shape)

print("\ny test batch",y_test_batch.shape)

print("\ny hat batch",y_hat_batch.shape)

X train -  (2620, 250, 25)
y train - (2620, 10)

X test batch- (260, 250, 25)

y test batch (260, 10)

y hat batch (260, 10)

### 1. SHAP implementation using Auto encoders on generic numerical dataset

1. The dataset used is **Boston Housing dataset**. It is not a time series dataset but the problem is anomaly detection using an auto encoder. <br>
2. For comparison, I have printed the dataset's shape along with their model summary. <br>
3. It has **13 features**. <br>
4. As it is a normal auto encoder, the input data is two dimensional. 

**Reference** <br>
https://github.com/liuyilin950623/SHAP_on_Autoencoder

In [31]:
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

Xb, yb = shap.datasets.boston()

std = StandardScaler()
X_standard = std.fit_transform(Xb)
X_trainn, X_testt = train_test_split(X_standard)

print("Dataset shape:",Xb.shape)
print("X train:",X_trainn.shape)
Xb

Dataset shape: (506, 13)
X train: (379, 13)

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT
0,0.00632,18.0,2.31,0.0,0.538,6.575,65.2,4.0900,1.0,296.0,15.3,396.90,4.98
1,0.02731,0.0,7.07,0.0,0.469,6.421,78.9,4.9671,2.0,242.0,17.8,396.90,9.14
2,0.02729,0.0,7.07,0.0,0.469,7.185,61.1,4.9671,2.0,242.0,17.8,392.83,4.03
3,0.03237,0.0,2.18,0.0,0.458,6.998,45.8,6.0622,3.0,222.0,18.7,394.63,2.94
4,0.06905,0.0,2.18,0.0,0.458,7.147,54.2,6.0622,3.0,222.0,18.7,396.90,5.33
...,...,...,...,...,...,...,...,...,...,...,...,...,...
501,0.06263,0.0,11.93,0.0,0.573,6.593,69.1,2.4786,1.0,273.0,21.0,391.99,9.67
502,0.04527,0.0,11.93,0.0,0.573,6.120,76.7,2.2875,1.0,273.0,21.0,396.90,9.08
503,0.06076,0.0,11.93,0.0,0.573,6.976,91.0,2.1675,1.0,273.0,21.0,396.90,5.64
504,0.10959,0.0,11.93,0.0,0.573,6.794,89.3,2.3889,1.0,273.0,21.0,393.45,6.48
505,0.04741,0.0,11.93,0.0,0.573,6.030,80.8,2.5050,1.0,273.0,21.0,396.90,7.88

**Model summary for this implementation:** <br>
![title](images/SHAP_model_other.png)

### 2. LIME Implementation using LSTM in Co2 dataset

1. CO2 dataset has 2 features. This is a classification problem but data is time series. <br>
2. They have pre-processed the data with respect to 12 timesteps. <br>
3. Thus their input shape is **(2270, 12, 2)** and output shape is **(2270, 2)**.

**Reference** <br>
https://github.com/marcotcr/lime/blob/master/doc/notebooks/Lime%20with%20Recurrent%20Neural%20Networks.ipynb

![title](images/LIME.png)

### Wrap-up:

If we compare our model with the two above model summary and data shape, it is pretty evident that the input and output feature shapes should be the same. <br>
1. First implementation has 13 input features and output prediction also has 13 features.
2. Second implementation has 2 input features and output also has 2 features.

From these obseravtions, we can also see that SHAP and LIME worked as expected with both datasets and models without any errors or exceptions as the input and output shapes are equal.